import React, { useEffect, useRef, useState } from "react";
import { getMyTicket, getMyTicketQr, getMyTickets } from "../services/api";

const display = (value) => typeof value === "string" ? value.slice(0, 16).replace("T", " ") : "—";
const mask = (code) => !code ? "—" : code.length <= 8 ? code : `${code.slice(0, 4)}••••••••${code.slice(-4)}`;

function MyTickets({ token, events, registrations, onUnauthorized, onBrowseEvents }) {
  const [tickets, setTickets] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [detail, setDetail] = useState(null), [detailLoading, setDetailLoading] = useState(false), [detailError, setDetailError] = useState("");
  const [qrUrl, setQrUrl] = useState(null), [qrTicketId, setQrTicketId] = useState(null), [qrLoading, setQrLoading] = useState(false), [qrError, setQrError] = useState("");
  const detailSeq = useRef(0), qrSeq = useRef(0), qrController = useRef(null);
  useEffect(() => { const controller = new AbortController(); setLoading(true); getMyTickets(token, controller.signal).then(setTickets).catch((e) => { if(e.name==="AbortError")return;if(e.status===401)onUnauthorized();else setError(e.status===403?"You do not have permission to access tickets.":e.status===0?"Unable to connect to the server.":"Unable to load tickets."); }).finally(()=>{if(!controller.signal.aborted)setLoading(false)}); return()=>controller.abort(); }, [token,onUnauthorized]);
  useEffect(() => () => { if (qrUrl) URL.revokeObjectURL(qrUrl); }, [qrUrl]);
  useEffect(() => () => qrController.current?.abort(), []);
  const registrationMap = new Map(registrations.map((item)=>[item.id,item])), eventMap = new Map(events.map((item)=>[item.id,item]));
  const eventName = (ticket) => { const registration=registrationMap.get(ticket.registration_id); return registration ? eventMap.get(registration.event_id)?.title || `Event #${registration.event_id}` : "Event unavailable"; };
  const closeQr=()=>{qrController.current?.abort();setQrUrl(null);setQrTicketId(null);setQrError("");setQrLoading(false)};
  const openDetail=async(id)=>{const seq=++detailSeq.current;setDetailLoading(true);setDetailError("");try{const item=await getMyTicket(id,token);if(seq===detailSeq.current)setDetail(item)}catch(e){if(seq!==detailSeq.current)return;if(e.status===401)onUnauthorized();else setDetailError(e.status===404?"Ticket not found.":e.status===403?"You do not have permission to access this ticket.":"Unable to load ticket information.")}finally{if(seq===detailSeq.current)setDetailLoading(false)}};
  const showQr=async(ticket)=>{if(ticket.status!=="ACTIVE")return;qrController.current?.abort();setQrUrl(null);setQrTicketId(ticket.id);setQrError("");setQrLoading(true);const controller=new AbortController();qrController.current=controller;const seq=++qrSeq.current;try{const blob=await getMyTicketQr(ticket.id,token,controller.signal);if(seq!==qrSeq.current||controller.signal.aborted)return;setQrUrl(URL.createObjectURL(blob))}catch(e){if(e.name==="AbortError"||seq!==qrSeq.current)return;if(e.status===401)onUnauthorized();else setQrError(e.status===404?"Ticket not found.":e.status===403?"You do not have permission to access this ticket.":e.status===409?"This ticket is no longer active.":e.status===0?"Unable to connect to the server.":"Unable to load the QR code.")}finally{if(seq===qrSeq.current)setQrLoading(false)}};
  if(loading)return <div className="state-panel"><div className="app-loader"/><p>Loading tickets...</p></div>;
  if(error)return <div className="state-panel error-panel"><strong>Unable to load tickets</strong><p>{error}</p></div>;
  return <section className="my-tickets"><div className="dashboard-title-row"><div><p className="eyebrow">EVENT ACCESS</p><h1>My Tickets</h1><p>View your event tickets and present an active QR code to staff.</p></div></div>{tickets.length===0?<div className="state-panel"><strong>You do not have any tickets yet.</strong><button className="primary-button" onClick={onBrowseEvents}>Browse Events</button></div>:<div className="ticket-layout"><div className="ticket-list">{tickets.map((ticket)=><article className={`ticket-card ${detail?.id===ticket.id?"selected":""}`} key={ticket.id}><div><span className={`ticket-status status-${ticket.status.toLowerCase()}`}>{ticket.status}</span><h2>{eventName(ticket)}</h2></div><span className="ticket-code">{mask(ticket.ticket_code)}</span><p>Issued {display(ticket.issued_at)}</p>{ticket.status==="VOID"&&<p>This ticket is no longer active.</p>}<div className="ticket-actions"><button className="secondary-button" onClick={()=>openDetail(ticket.id)}>View Ticket</button>{ticket.status==="ACTIVE"&&<button className="primary-button" onClick={()=>showQr(ticket)} disabled={qrLoading&&qrTicketId===ticket.id}>{qrLoading&&qrTicketId===ticket.id?"Loading QR code...":"Show QR"}</button>}</div></article>)}</div>{(detail||detailLoading||detailError||qrTicketId)&&<aside className="ticket-detail-panel">{detailLoading?<div className="compact-state"><div className="app-loader"/><p>Loading ticket...</p></div>:detail&&<><div className="editor-heading"><div><p className="eyebrow">TICKET DETAILS</p><span className={`ticket-status status-${detail.status.toLowerCase()}`}>{detail.status}</span></div><button className="text-button" onClick={()=>setDetail(null)}>Close</button></div><h2>{eventName(detail)}</h2><dl><div><dt>Ticket code</dt><dd className="ticket-code full">{detail.ticket_code}</dd></div><div><dt>Issued</dt><dd>{display(detail.issued_at)}</dd></div><div><dt>Updated</dt><dd>{display(detail.updated_at)}</dd></div></dl></>}{detailError&&<div className="inline-message error-message">{detailError}</div>}{qrTicketId&&<div className="qr-panel"><div className="editor-heading"><h3>QR Code</h3><button className="text-button" onClick={closeQr}>Close QR</button></div>{qrLoading&&<div className="compact-state"><div className="app-loader"/><p>Loading QR code...</p></div>}{qrError&&<div className="inline-message error-message">{qrError}</div>}{qrUrl&&<><img src={qrUrl} alt="QR code for event ticket"/><p>Present this QR code to event staff for check-in.</p></>}</div>}</aside>}</div>}</section>;
}
export default MyTickets;
