EVENT_STATUS_DRAFT = "DRAFT"
EVENT_STATUS_PUBLISHED = "PUBLISHED"
EVENT_STATUS_CANCELLED = "CANCELLED"
EVENT_STATUS_COMPLETED = "COMPLETED"

ALL_EVENT_STATUSES = {
    EVENT_STATUS_DRAFT,
    EVENT_STATUS_PUBLISHED,
    EVENT_STATUS_CANCELLED,
    EVENT_STATUS_COMPLETED,
}
